### ISSUE TITLE
Microsoft.FSharp.Collections.SeqModule.Item missing exception in example

### ISSUE THREAD

**Issue by danielrbradley** [fslaborg/FsLab#135]
When trying to run the example on a Windows 7 computer with VS 2015 installed, but running through VS Code with Ionide installed. I receive the following exception:

```
System.MissingMethodException: Method not found: '!!0 Microsoft.FSharp.Collections.SeqModule.Item(Int32, System.Collections.Generic.IEnumerable`1<!!0>)'.
   at XPlot.GoogleCharts.Data.makeDataTable(IEnumerable`1 series, FSharpOption`1 labels)
   at XPlot.GoogleCharts.GoogleChart.Create(IEnumerable`1 data, FSharpOption`1 labels, Options options, ChartGallery type)
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in c:\[snip]\FsLab.Templates-basic\Tutorial.fsx:line 31
Stopped due to error
```

**Comment by tpetricek** [comment]
I tested this on Win 10 and it works fine for me. What version of F# Core are you running this against? You can run the following in F# Interactive:

    typeof<_ -> _>.Assembly.FullName

**Comment by dsyme** [comment]
You may need to adjust Ionide to use a different F# Interactive, the one from tools 10.1 rather than 4.1
